# Generated by Django 3.1.1 on 2020-09-07 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 14, 10, 41, 40, 807473, tzinfo=utc)),
        ),
    ]
